---
- hosts: websever
  tasks:      
    - name: Log into DockerHub
      docker_login:
        registry: docker.io
        username: siddeshg672
        password: "{{ docker_password }}"
        
    - name: pull an image
      docker_image:
        name: "siddeshg672/devopsapp:test-deploy_{{ BUILD_NUMBER }}"
        source: pull

    - name: remove container
      docker_container:
        name: devopsAppDeploy
        state: absent
        
    - name: create a application container
      docker_container:
        name: devopsAppDeploy
        image: "siddeshg672/devopsapp:test-deploy_{{ BUILD_NUMBER }}"
        state: started
        ports:
          - "8111:8080"
